---
stages:
  - check

run-pre-commit:
  stage: check
  image: harbor.maxiv.lu.se/kits-sw/pre-commit:latest
  tags:
    - kubernetes
  script:
    - pre-commit run --all-files
  rules:
    # Disable detached pipeline on MR
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'
      exists:
        - .pre-commit-config.yaml
