---
variables:
  PRE_COMMIT_IMAGE: harbor.maxiv.lu.se/kits-sw/pre-commit:latest
  PYPI_IMAGE: harbor.maxiv.lu.se/dockerhub/library/python:3
  PYPI_ENABLED: "true"

stages:
  - check
  - build
  - test
  - publish

.run-pre-commit:
  stage: check
  image: $PRE_COMMIT_IMAGE
  tags:
    - kubernetes
  script:
    - pre-commit run --all-files
  rules:
    # Disable detached pipeline on MR
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_BRANCH || $CI_COMMIT_TAG'
      exists:
        - .pre-commit-config.yaml

build-pypi-package:
  stage: build
  tags:
    - kubernetes
  image: $PYPI_IMAGE
  script:
    - clone_remoterepo_if_defined
    - pip install --upgrade pip
    - pip install --upgrade build
    - python -m build
    - |
      if [[ ! -z "$CI_COMMIT_TAG" ]]; then
        echo "Checking that the python version matches the git tag..."
        pip install wheel-filename
        version=$(python -c "import glob, wheel_filename; print(wheel_filename.parse_wheel_filename(glob.glob('dist/*.whl')[0]).version)")
        if [[ "$version" != "$CI_COMMIT_TAG" ]]; then
          echo "Invalid tag $CI_COMMIT_TAG! It should match the python package version $version"
          exit 1
        else
          echo "OK!"
        fi
      fi
  artifacts:
    expire_in: 1 week
    paths:
      - dist/
 
